modLoader = "kotlinforforge"
loaderVersion = "[4,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "Apache 2.0" #mandatory
issueTrackerURL = "https://github.com/RealYusufIsmail/Armour-and-Tools-Mod/issues"
[[mods]]
modId = "armourandtoolsmod"
version = "1.20.1-1.0.7.beta4"
displayName = "Armour and Tools Mod"
logoFile = "logo.png"
updateJSONURL = "https://forge.curseupdate.com/480779/armourandtoolsmod"
description = '''
This Minecraft mod adds new armours and tools, as well as new dimensions and bosses to the game. However, some features are still being developed and will be added in the future. With the new armour and tools, players can customize their play style and approach combat in new ways. The new dimensions offer unique challenges, enemies, and rewards, while the bosses provide exciting battles and new strategies to master. (To be added). Overall, this mod provides a fresh and exciting experience for Minecraft players, with more features to come in the future such as lightsabres and thors hammers,
'''

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.armourandtoolsmod]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.armourandtoolsmod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1, 1.21)"
ordering = "NONE"
side = "BOTH"

[[dependencies.armourandtoolsmod]]
modId = "realyusufismailcore"
mandatory = true
versionRange = "[1.20.1-1.0.1,)"
ordering = "NONE"
side = "BOTH"