modLoader = "kotlinforforge"
loaderVersion = "[4,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "Apache 2.0" #mandatory
issueTrackerURL = "https://github.com/RealYusufIsmail/Armour-and-Tools-Mod/issues"
updateJSONURL = "https://raw.githubusercontent.com/RealYusufIsmail/Armour-and-Tools-Mod/main/update.json"
[[mods]]
modId = "armourandtoolsmod"
version = "${file.jarVersion}"
displayName = "Armour and Tools Mod"

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.armourandtoolsmod]]
modId = "forge"
mandatory = true
versionRange="[45,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.armourandtoolsmod]]
modId = "minecraft"
mandatory = true
versionRange= "[1.19.4,1.20)"
ordering = "NONE"
side = "BOTH"

[[dependencies.armourandtoolsmod]]
modId = "realyusufismailcore"
mandatory = true
versionRange = "[1.19-1.0.6,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.armourandtoolsmod]]
modId = "patchouli"
mandatory = false
versionRange = "[1.19.3-78,)"
ordering = "NONE"
side = "BOTH"
