name: Feature Request
description: Request a new feature
labels: [ enhancement ]
assignees: [ RealYusufIsmail ]
body:
  - type: markdown
    attributes:
      value: |-
        Please ask questions in [our Discussions](https://github.com/RealYusufIsmail/Armour-and-Tools-Mod/discussions)
        
        Keep in mind that this isn't the place to learn Kotlin.  
        Please head over to [StackOverflow](https://stackoverflow.com/questions/tagged/kotlin) for your general programming questions.
  - type: checkboxes
    attributes:
      label: General Troubleshooting
      description: You confirm to have made the following checks first.
      options:
        - label: I have checked for similar issues on the Issue-tracker.
          required: true
        - label: I have checked the branches or the maintainers' PRs for upcoming features.
          required: true
  - type: textarea
    attributes:
      label: "Feature Request"
      description: "Provide a small description of the feature you want to have added."
      placeholder: "Armour and Item mod should get ..."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Example Use-Case"
      description: |-
        Provide some code or describe a possible use-case for this feature.
        
        The provided text will be rendered as Kotlin code, so you don't have to provide a Code block for it.
      placeholder: "fun newMethod() { ... }"
      render: kotlin
