modLoader = "kotlinforforge"
loaderVersion = "[4,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "Apache 2.0" #mandatory
issueTrackerURL = "https://github.com/RealYusufIsmail-Mc-Mods/TemporalSmith/issues"
[[mods]]
modId = "temporalsmith"
version = "1.20.2-1.0.0.beta9"
displayName = "TemporalSmith: Aetheric Arsenal Expansion"
logoFile = "logo.png"
updateJSONURL = "https://forge.curseupdate.com/480779/temporalsmith"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/temporalsmith"
description = '''
Descend into the boundless realms of TemporalSmith, where time intertwines with the craft of the Aetheric Arsenal. Unleash the power of enchanted swords and tools forged beyond the constraints of time. Explore mystical dimensions, each brimming with unique challenges and treasures. Elevate your Minecraft experience with a fusion of temporal mastery, otherworldly landscapes, and an expansive array of armaments. The journey awaits; delve into the time-woven secrets of TemporalSmith. (A lot of stuff to be added)'''

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.temporalsmith]]
modId = "neoforge"
mandatory = true
versionRange = "[20.2, 20.3)"
ordering = "NONE"
side = "BOTH"

[[dependencies.temporalsmith]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.2, 1.21)"
ordering = "NONE"
side = "BOTH"

[[dependencies.temporalsmith]]
modId = "realyusufismailcore"
mandatory = true
versionRange = "[1.20.2-1.1.2,)"
ordering = "NONE"
side = "BOTH"